### ISSUE TITLE
the sign-in magic link expires 

### ISSUE THREAD

**Issue by rcsang** [1729/content#40]
I could not log in on 1729.com with the magic link that is sent to my email. I do get different links, but all of them redirect to "The magic link is invalid or expired."

**Comment by Git-Prabhu** [comment]
I have a similar issue. Here's a screenshot and details if it helps troubleshoot:
- Browser: Google Chrome
- Steps to reproduce: Subscribe and provide email
- Magic link is received in email
- Clicking on link takes to the message in attached screenshot
<img width="932" alt="1729Networkstate" src="https://user-images.githubusercontent.com/25622868/155645170-feecdbf6-4ba4-4e0d-9f1a-bd69ea24278e.PNG">
